---

net_object:
  DMZ_WEB_SERVERS:
    networks:
      - subnet: "10.10.0.1"
        mask: "255.255.255.255"
      - subnet: "10.10.0.2"
        mask: "255.255.255.255"
      - subnet: "10.10.0.3"
        mask: "255.255.255.255"

service_objects:
  WEB_PORTS:
    protocol: "tcp"
    ports:
      - type: 'match'
        port: 'www'
      - type: 'match'
        port: 'https'
access_list:
  name: "EXTERNAL_ALLOWED_INBOUND"
  elements:
    - source: "any"
      destination: "object-group DMZ_WEB_SERVERS"
      port: "object-group WEB_PORTS"
      action: "permit"
      protocol: "tcp"
#    - source: "192.168.100.0 255.255.255.0"
#      destination: "any"
#      port: "www"
#      action: "permit"
#      protocol: "tcp"
#
#    - source: "192.168.100.0 255.255.255.0"
#      destination: "any"
#      action: "deny"
#      protocol: "ip"
